# Generated by Django 3.2.7 on 2021-11-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('repassword', models.CharField(max_length=120)),
            ],
        ),
    ]
