# Generated by Django 3.2.7 on 2021-11-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_register', '0002_personal_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
