# Generated by Django 3.2.7 on 2021-11-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_register', '0003_alter_personal_details_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_details',
            name='title',
            field=models.CharField(default=True, max_length=120),
        ),
    ]
