# Generated by Django 3.2.7 on 2021-11-24 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_register', '0004_personal_details_title'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='personal_details',
            table='myapp_image',
        ),
    ]
