# Generated by Django 3.2.7 on 2021-11-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_register', '0006_alter_personal_details_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal_details',
            old_name='image',
            new_name='image_ID',
        ),
        migrations.RenameField(
            model_name='personal_details',
            old_name='title',
            new_name='title_ID',
        ),
        migrations.AddField(
            model_name='personal_details',
            name='image_face',
            field=models.ImageField(default=True, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal_details',
            name='title_face',
            field=models.CharField(default=True, max_length=120),
        ),
    ]
