# Generated by Django 3.2.7 on 2021-11-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_register', '0007_auto_20211124_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_details',
            name='image_ID',
        ),
        migrations.RemoveField(
            model_name='personal_details',
            name='title_ID',
        ),
    ]
