# Generated by Django 3.2.7 on 2021-11-24 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_register', '0008_auto_20211124_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal_details',
            old_name='image_face',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='personal_details',
            old_name='title_face',
            new_name='title',
        ),
    ]
