# Generated by Django 3.2.7 on 2021-11-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_register', '0010_auto_20211124_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_details',
            name='image_ID',
            field=models.ImageField(default=True, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal_details',
            name='title_ID',
            field=models.CharField(default=True, max_length=120),
        ),
    ]
